---
- name: Add config file to a server
  become: yes
  hosts: 192.168.1.168
  roles: 
    - roles/oleg.nagios.server

- name: Configure nagios client
  hosts: 192.168.1.167
  become: yes
  roles:
    - oleg.nagios-client    