---
# tasks file for /home/ansible/roles/feruza.mysql
- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install Requires packages
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ package_list }}"  


- name: Start and enable required services
  service:
    state: started
    name: "{{ item }}"
    enabled: yes
  loop: "{{ service_list }}"  


- name: Mysql secure installation
  community.mysql.mysql_user:
    name: root
    password: "{{ roots_passwd }}"
    login_password: "{{ roots_passwd }}"


- name: Copy phpmyadmin Template
  template:
    dest: /etc/httpd/conf.d/phpMyAdmin.conf
    src: phpMyAdmin.conf.j2 

- name: Add services to the firewall
  firewalld:
    state: enabled
    service: "{{ item }}"
    permanent: yes
    immediate: yes
  loop: "{{ firewall_services }}"

- name: Restart httpd
  service:
    name: httpd
    state: restarted

- name: Copy identity file
  template:
    dest: /root/.my.cnf
    src: my.cnf.j2  

- name: Copy database query file
  copy:
    src: database.sql
    dest: /root/database.sql 
      
#- name: Adding entries to Database
#  shell:
#    chdir: /root
#    cmd: mysql < database.sql

#- name: Dump SpringDevOps2021 databse
#  mysql_db:
#    name: SpringDevOps2021
#    state: dump
#    target: /tmp/SpringDevOps2021_backup.sql


- name: Remove databse SpringDevOps2021
  mysql_db:
    name: SpringDevOps2021
    state: absent

- name: Create SpringDevOps2021 databse
  mysql_db:
    state: present
    name: SpringDevOps2021
    
- name: Recover from backup
  mysql_db:
    name: SpringDevOps2021
    state: import
    target: /tmp/SpringDevOps2021_backup.sql